"""new_generic_narrative_column

Revision ID: 013eaac40ce6
Revises: 8ee1a0cfcb20
Create Date: 2025-11-23 08:14:54.814704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '013eaac40ce6'
down_revision: Union[str, None] = '8ee1a0cfcb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('events', sa.Column('generated_narrative', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'generated_narrative')
    # ### end Alembic commands ###
