"""refactor_schema_add_conversations_channels_assistants

Revision ID: 4683d539f4ad
Revises: a1b2c3d4e5f6
Create Date: 2025-11-22 21:53:00.723196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4683d539f4ad'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('ai_memory_assistants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memory_assistants_id'), 'ai_memory_assistants', ['id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('telegram', 'whatsapp', 'web', name='channeltypeenum'), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'identifier', name='unique_channel_type_identifier')
    )
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_type'), 'channels', ['type'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='conversationstatusenum'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['ai_memory_assistants.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_assistant_id'), 'conversations', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_conversations_channel_id'), 'conversations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('user', 'assistant', name='messagedirectionenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('events', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('ai_context', sa.Text(), nullable=True))
    op.add_column('memories', sa.Column('message_id', sa.Integer(), nullable=True))
    op.add_column('memories', sa.Column('s3_url', sa.String(), nullable=True))
    # Create enum type for media_type before adding column
    op.execute("CREATE TYPE mediatypeenum AS ENUM ('image', 'video', 'audio', 'text', 'document')")
    op.add_column('memories', sa.Column('media_type', sa.Enum('image', 'video', 'audio', 'text', 'document', name='mediatypeenum'), nullable=True))
    op.add_column('memories', sa.Column('memory_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('memories_embedding_idx', table_name='memories', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_memories_message_id'), 'memories', ['message_id'], unique=False)
    op.create_foreign_key(None, 'memories', 'messages', ['message_id'], ['id'])
    op.drop_column('memories', 'image_url')
    # Recreate HNSW index for vector embeddings
    op.execute("""
        CREATE INDEX memories_embedding_idx ON memories
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
    """)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'phone_number')
    # Drop HNSW index before making changes
    op.execute("DROP INDEX IF EXISTS memories_embedding_idx;")
    op.add_column('memories', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_index(op.f('ix_memories_message_id'), table_name='memories')
    op.create_index('memories_embedding_idx', 'memories', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('memories', 'memory_metadata')
    op.drop_column('memories', 'media_type')
    # Drop the media type enum
    op.execute("DROP TYPE IF EXISTS mediatypeenum")
    op.drop_column('memories', 's3_url')
    op.drop_column('memories', 'message_id')
    op.drop_column('events', 'ai_context')
    op.drop_column('events', 'summary')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assistant_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_channels_type'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_ai_memory_assistants_id'), table_name='ai_memory_assistants')
    op.drop_table('ai_memory_assistants')
    # ### end Alembic commands ###
