"""add-column-image-description-to-messages

Revision ID: 8ee1a0cfcb20
Revises: 204c6070933e
Create Date: 2025-11-23 05:38:33.783226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ee1a0cfcb20'
down_revision: Union[str, None] = '204c6070933e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.drop_index('memories_embedding_idx', table_name='memories', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('messages', sa.Column('image_description', sa.Text(), nullable=True))
    op.drop_index('messages_embedding_idx', table_name='messages', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('messages_embedding_idx', 'messages', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('messages', 'image_description')
    op.create_index('memories_embedding_idx', 'memories', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
