"""add video_s3_url to messages

Revision ID: d4b3ecc071bd
Revises: 8ee1a0cfcb20
Create Date: 2025-11-23 08:09:51.703887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4b3ecc071bd'
down_revision: Union[str, None] = '8ee1a0cfcb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('messages', sa.Column('video_s3_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'video_s3_url')
    # ### end Alembic commands ###
