"""add embedding to messages

Revision ID: de934a404c98
Revises: 4683d539f4ad
Create Date: 2025-11-22 23:23:21.272528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

revision: str = 'de934a404c98'
down_revision: Union[str, None] = '4683d539f4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # Add embedding column to messages
    op.add_column('messages', sa.Column('embedding', Vector(1024), nullable=True))
    
    # Create HNSW index for messages embeddings
    # HNSW (Hierarchical Navigable Small World) is optimal for high-dimensional vectors
    # Using cosine distance with reasonable performance parameters
    op.execute('''
        CREATE INDEX IF NOT EXISTS messages_embedding_idx
        ON messages
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
    ''')
    
    # Recreate memories index (it was incorrectly detected as removed)
    op.execute('''
        CREATE INDEX IF NOT EXISTS memories_embedding_idx
        ON memories
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop messages embedding index
    op.execute('DROP INDEX IF EXISTS messages_embedding_idx;')
    
    # Drop embedding column from messages
    op.drop_column('messages', 'embedding')
    # ### end Alembic commands ###
