"""add photo_s3_url to messages

Revision ID: eada2497970c
Revises: de934a404c98
Create Date: 2025-11-23 00:30:31.103583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eada2497970c'
down_revision: Union[str, None] = 'de934a404c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('messages', sa.Column('photo_s3_url', sa.Text(), nullable=True))
    
    # Recreate embedding indexes if they don't exist
    op.execute('''
        CREATE INDEX IF NOT EXISTS messages_embedding_idx
        ON messages
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
    ''')
    
    op.execute('''
        CREATE INDEX IF NOT EXISTS memories_embedding_idx
        ON memories
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'photo_s3_url')
    # ### end Alembic commands ###
