"""add_event_invite_code

Revision ID: ff168deb9a00
Revises: eada2497970c
Create Date: 2025-11-22 23:47:02.063367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff168deb9a00'
down_revision: Union[str, None] = 'eada2497970c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # First add column as nullable
    op.add_column('events', sa.Column('invite_code', sa.String(length=20), nullable=True))
    
    # Generate invite codes for existing events
    op.execute("""
        UPDATE events 
        SET invite_code = UPPER(SUBSTRING(MD5(RANDOM()::TEXT || id::TEXT) FROM 1 FOR 8))
        WHERE invite_code IS NULL
    """)
    
    # Now make it not nullable
    op.alter_column('events', 'invite_code', nullable=False)
    
    # Create unique index
    op.create_index(op.f('ix_events_invite_code'), 'events', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_invite_code'), table_name='events')
    op.drop_column('events', 'invite_code')
    # ### end Alembic commands ###
